name: Release
on: [workflow_dispatch] # Manual trigger
jobs:
  buildJava:
    runs-on: ubuntu-20.04
    container:
      image: openjdk:17-jdk
      options: --user root
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build publish --stacktrace
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

  buildNatives:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'
      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build
      - run: ./gradlew jpackage publish --stacktrace
        env:
          MAVEN_URL: ${{ secrets.MAVEN_URL }}
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
          PLATFORM: "windows"
# TODO: It would be nice to distribute a macos version, but it's $99 a year and nobody on our
# dev team seems to own a mac.